language: python
dist: bionic
python:
  - 3.6
  - 3.7
  - 3.8
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_existing: true
  user: mgeiger
  password:
    secure: dAeirqsyFZfLgdcU8GNlpCnqYAF91GGqKYBaI/sNFJl0+t7wh274ZPsE2d9/Rggq3LwnK0/wCC7C3wbZ4tFLDmqnB9f1nMitdfUyOFD8gDxwmdItYFZmqYNujkbLty+Sx91Z8LvI75RbKVPLRD6aNVMcP4bNpB3IMc6czOYbaJEW8lF+yEU34y8SLTeyQp9avsUayV6NW5F33I7rTUlHmJwVpGdBMoTpQMwaYpyP1/rBznmWwFXNqexdM4zaYegmY+WwBRCfcZ3sBNpEMOL04NyHEhZLCa3bANVTFY92CmAKbBzECa/IDcHGP5fp1+FfnwSurMF93WzcFSh05cFcLDTJMWV520/xjp+uGGlC2LnIIYL/DlrYSXze3JWRtIp8j1PJTL8uNs+1kcBwB4OKqxKCrmIWBcES+SDhIdwkuvbKIRScn85Kzy8+yO4vweDDNJL5w9jShhHWSj0gzSvQsQTM+X+i2nXuy5B/y/JbzuygPQkp4oNbh87SedhDPKaK6F1/D48C4HiYiJKT5SzIcnI5DXNR5W85144+GZn3VpwpNUme6EPiuwvkv3Khf+JfUqdt2mAI2Q9v8EhnHnuYBl8qyhVI2cfmOS3ZYmvWcbxvoJqwi3/jeL8BCiRLDCEW+Gmls4O7XWV2ic0xXBpnw0DRjYa53KgFRqYYygSULu4=
  on:
    tags: true
    repo: mgeiger/gotime
    python: 3.7
    branch: master
notifications:
  slack:
    secure: fhWGn5jdoTCjtGgoU5EH3q58PIWLC8Jddcnvuz0ca0dFIyZUJ3qwUt9Na6agoovaO1k8AVJxF/v+TUbji/9L5J20UegWZLZxb3OFDlxjMdLYsY5eqgKyXbVY6e+gVaXnEjVfVOR0NyljAPJbv6yXGyzPNioJXsA7pkPJoe5OKCnDVrQdVdFl3mY+Xbv59wU8NWfnVm5u9128R8KfRJ6WuJs7/i/RIMoVuw5wvNt+G8tQpViNa89VJ2Lz4pT/G81QWCY+ExUvI9vJdVaGyF7eHZCELnF3YScnLstRWhiNhKo5nAbMd2wROfXMXmXpATzPI0Y7jkePhGix/B3VJChPDoQzGWcbxyDcnJ4QcjO1lrCocykm/ddAtng5D3DK9zz76ZhnIAkabKSSuMxqN3NYARTSLvESaD8ozylCzH4UdjCIc5/xRMH/mNYXJwixCW0U0YNNRlLMwnfTLrLe3hIkTgj7ZMhDOcjWBbHJQZhNlP0pEWqCdHFhugnu6M2XK2ij9iVG9LX/iu4D8D6DZA/dwwTMgUMlzZkH9nXv2S01Z8T6iES9X+zYA5v+mLeHMKdfKmg8IRcd++nwgFynJ+yf6UxouZc5BmXpSAdbAxRogVul/rHpipDPgg8IpI8E4X/0pbC2Mb+i+9y/n4Xa8rXZXSuHyCni19bHAdPmYCtg56o=
